apiVersion: apps/v1
kind: Deployment
metadata:
    name: mirrorlit-deploy
spec:
    # 3으로 바꾸기
    replicas: 2
    selector:
        matchLabels:
            app: mirrorlit
    template:
        metadata:
            labels:
                app: mirrorlit
        spec:
            containers:
                - name: mirrorlit
                  image: chsl123/mirrorlit:latest
                  envFrom:
                      - secretRef:
                        name: mirrorlit-secret
                  ports:
                      - containerPort: 3000
